name: RoseTimber
version: '@version@'
author: Esophose
main: dev.rosewood.rosetimber.RoseTimber
api-version: '1.13'
softdepend: [ mcMMO, CoreProtect, PlaceholderAPI ]
permissions:
  rosetimber.basecommand:
    description: The base command permission for being able to see the RoseStacker command
    default: true
  rosetimber.*:
    description: Inherits all plugin permissions
    children:
      rosetimber.reload: true
      rosetimber.toggle: true
      rosetimber.help: true
      rosetimber.chop: true
      rosetimber.bonusloot: true
      rosetimber.bypasscooldown: true
  rosetimber.chop:
    description: Allows players to trigger the trees toppling down effect
    default: op
  rosetimber.bonusloot:
    description: Applies a tree loot multiplier
    default: op
  rosetimber.reload:
    description: Reloads the configuration file
    default: op
  rosetimber.bypasscooldown:
    description: Allows a player to bypass the tree topple cooldown
    default: op
